### ISSUE TITLE
Which method you used to aggregate the pairwise scores?

### ISSUE THREAD

**Issue by binzhouu** [castorini/duobert#10]
The paper mentions "At inference time, we aggregate the pairwise scores pi,j so that each document receives a sin- gle score si. We investigate five different aggregation methods (SUM, BINARY, MIN, MAX, and SAMPLE)"

I didn't see this part of code.

**Comment by rodrigonogueira4** [comment]
Thanks for asking and sorry about not adding a comment mentioning it.

We use the SUM method: https://github.com/castorini/duobert/blob/24c7a16f847bad4ad79a07efc58d04bce70ebc6c/run_duobert_msmarco.py#L443

**Comment by binzhouu** [comment]
Thanks!
